### PR TITLE
allow use addHandler with array of contentType

### PR DESCRIPTION
**Pull request by taina0407**
example 
```
let sitemapsParser = supercrawler.handlers.sitemapsParser();
crawler.addHandler([
  "text/xml",
  "application/x-gzip",
  "application/gzip",
  "application/octet-stream"], sitemapsParser);
```

### CODE REVIEW

**Comment by cbess** [comment]
@brendonboshell Will this get merged?

**Comment by brendonboshell** [comment]
@cbess I think it will need a few changes:

1. An array like `["text"]` should match `text/html`, `text/xml`, etc. This will make it consistent with the API when the first argument is a string.
2. Unit tests.
3. Update the documentation to include calling `addHandler` with an array as the first argument.

**Comment by cbess** [comment]
I agree with every point except for `#1`. I think being explicit is preferred in this case. I would vote *breaking* consistency for the sake of *safety*.

**Comment by brendonboshell** [comment]
Thanks, and apologies for the delay merging this. Published as 1.7.0.

**Pull request merged**
